data <- read.table("household_power_consumption.txt",sep=";",header=T)
data[,1]  <- as.Date(data[,1], "%d/%m/%Y")
data1 <- data[which(data[,1]=="2007-02-01"),]
data2 <- data[which(data[,1]=="2007-02-02"),]
newdata <- rbind(data1,data2)
weekday <- paste(newdata$Date,newdata$Time)
weekday <- as.POSIXct(weekday) 
newdata$Global_active_power <- as.numeric(newdata$Global_active_power)
png(file="plot4.png", bg="transparent")
par(mfrow = c(2, 2))
plot(weekday,newdata$Global_active_power/1000,yaxt="n",ylab="Global Active Power",xlab="",type="l")
y<-seq(0,6,2)
axis(2,labels=y,at=0:3,las=3)
plot(weekday,newdata$Voltage,yaxt="n",ylab="Voltage",xlab="datetime",type="l")
y<-c(234,"",238,"",242,"",246)
axis(2,labels=y,at=c(800,1000,1200,1400,1600,1800,2000),las=3)
plot(weekday,newdata$Sub_metering_1,yaxt="n",ylab="Energy sub metering",xlab="",type="l",col="black")
y<-seq(0,30,10)
axis(2,labels=y,at=c(1,10,20,30),las=3)
lines(weekday,newdata$Sub_metering_2,col="red")
lines(weekday,newdata$Sub_metering_3,col="blue")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"),lty=1)
plot(weekday,newdata$Global_reactive_power,yaxt="n",ylab="Global_reactive_power",xlab="datetime",type="l")
y<-seq(0,0.5,0.1)
axis(2,labels=y,at=c(1,40,80,120,160,200),las=3)
dev.off()

